name: Auto Commit

on:
  schedule:
    - cron: "35 20 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "BProject-Developer"
          git config user.email "bprojectdeveloper@gmail.com"

      - name: Buat commit
        run: |
          echo "Update $(date)" >> log.txt
          git add log.txt
          git commit -m "auto update $(date)" || echo "No changes to commit"

      - name: Push ke repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
