name: Auto Commit

on:
  schedule:
    - cron: "47 20 * * *"
  workflow_dispatch:

# Pastikan workflow punya izin tulis ke repo
permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (dengan credential untuk push)
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config user.name "BProject-Developer"
          git config user.email "bprojectdeveloper@gmail.com"

      - name: Update log file
        run: |
          echo "Update: $(date -u)" >> log.txt
          git add log.txt
          git commit -m "auto update $(date -u)" || echo "No changes to commit"

      - name: Push changes ke main
        run: |
          git push origin HEAD:main